import { catalogUuid } from '../../soil-laboratory/catalogs/catalog-ids.js';
import type { VerificationStatus } from '../../types/physical-suitability.types.js';
import type {
  WaterParameter,
  WaterParameterCategory,
  WaterParameterDataType,
} from '../types/irrigation-water.types.js';
import { unitIdForCode } from './water-measurement-unit.catalog.js';

export type WaterParameterSeedDef = {
  code: string;
  canonicalName: string;
  turkishDisplayName: string;
  englishDisplayName: string;
  category: WaterParameterCategory;
  description: string | null;
  canonicalUnitCode: string | null;
  dataType: WaterParameterDataType;
  decimalPrecision: number | null;
  isDirectlyMeasured: boolean;
  isCalculated: boolean;
  isRequiredForIrrigationAssessment: boolean;
  displayOrder: number;
  source: string | null;
  verificationStatus: VerificationStatus;
};

/**
 * Seed catalog — Phase 2.2G.
 * No scientific classification ranges. Unknown fields stay null / Draft.
 */
export const WATER_PARAMETER_SEED: readonly WaterParameterSeedDef[] = [
  {
    code: 'WATER_PH',
    canonicalName: 'Water pH',
    turkishDisplayName: 'Su pH',
    englishDisplayName: 'Water pH',
    category: 'GENERAL',
    description: null,
    canonicalUnitCode: 'PH_UNIT',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 10,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'WATER_EC',
    canonicalName: 'Electrical conductivity',
    turkishDisplayName: 'Elektriksel iletkenlik',
    englishDisplayName: 'Electrical conductivity',
    category: 'SALINITY',
    description: null,
    canonicalUnitCode: 'DS_PER_M',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 20,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'TDS',
    canonicalName: 'Total dissolved solids',
    turkishDisplayName: 'Toplam çözünmüş katı madde',
    englishDisplayName: 'Total dissolved solids',
    category: 'SALINITY',
    description: null,
    canonicalUnitCode: 'MG_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 1,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 30,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'SODIUM',
    canonicalName: 'Sodium',
    turkishDisplayName: 'Sodyum',
    englishDisplayName: 'Sodium',
    category: 'MAJOR_CATION',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 40,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'CALCIUM',
    canonicalName: 'Calcium',
    turkishDisplayName: 'Kalsiyum',
    englishDisplayName: 'Calcium',
    category: 'MAJOR_CATION',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 50,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'MAGNESIUM',
    canonicalName: 'Magnesium',
    turkishDisplayName: 'Magnezyum',
    englishDisplayName: 'Magnesium',
    category: 'MAJOR_CATION',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 60,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'POTASSIUM',
    canonicalName: 'Potassium',
    turkishDisplayName: 'Potasyum',
    englishDisplayName: 'Potassium',
    category: 'MAJOR_CATION',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 70,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'BICARBONATE',
    canonicalName: 'Bicarbonate',
    turkishDisplayName: 'Bikarbonat',
    englishDisplayName: 'Bicarbonate',
    category: 'MAJOR_ANION',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 80,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'CARBONATE',
    canonicalName: 'Carbonate',
    turkishDisplayName: 'Karbonat',
    englishDisplayName: 'Carbonate',
    category: 'MAJOR_ANION',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 90,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'CHLORIDE',
    canonicalName: 'Chloride',
    turkishDisplayName: 'Klorür',
    englishDisplayName: 'Chloride',
    category: 'MAJOR_ANION',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 100,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'SULFATE',
    canonicalName: 'Sulfate',
    turkishDisplayName: 'Sülfat',
    englishDisplayName: 'Sulfate',
    category: 'MAJOR_ANION',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 110,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'BORON',
    canonicalName: 'Boron',
    turkishDisplayName: 'Bor',
    englishDisplayName: 'Boron',
    category: 'TOXICITY',
    description: null,
    canonicalUnitCode: 'MG_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 120,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'NITRATE',
    canonicalName: 'Nitrate',
    turkishDisplayName: 'Nitrat',
    englishDisplayName: 'Nitrate',
    category: 'NUTRIENT',
    description: null,
    canonicalUnitCode: 'MG_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 130,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'AMMONIUM',
    canonicalName: 'Ammonium',
    turkishDisplayName: 'Amonyum',
    englishDisplayName: 'Ammonium',
    category: 'NUTRIENT',
    description: null,
    canonicalUnitCode: 'MG_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 140,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'FLUORIDE',
    canonicalName: 'Fluoride',
    turkishDisplayName: 'Florür',
    englishDisplayName: 'Fluoride',
    category: 'TOXICITY',
    description: null,
    canonicalUnitCode: 'MG_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 150,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'IRON',
    canonicalName: 'Iron',
    turkishDisplayName: 'Demir',
    englishDisplayName: 'Iron',
    category: 'TOXICITY',
    description: null,
    canonicalUnitCode: 'MG_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 160,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'MANGANESE',
    canonicalName: 'Manganese',
    turkishDisplayName: 'Mangan',
    englishDisplayName: 'Manganese',
    category: 'TOXICITY',
    description: null,
    canonicalUnitCode: 'MG_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 3,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 170,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'TURBIDITY',
    canonicalName: 'Turbidity',
    turkishDisplayName: 'Bulanıklık',
    englishDisplayName: 'Turbidity',
    category: 'PHYSICAL',
    description: null,
    canonicalUnitCode: 'NTU',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 180,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'WATER_TEMPERATURE',
    canonicalName: 'Water temperature',
    turkishDisplayName: 'Su sıcaklığı',
    englishDisplayName: 'Water temperature',
    category: 'PHYSICAL',
    description: null,
    canonicalUnitCode: 'DEG_C',
    dataType: 'Decimal',
    decimalPrecision: 1,
    isDirectlyMeasured: true,
    isCalculated: false,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 190,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'SAR',
    canonicalName: 'Sodium adsorption ratio',
    turkishDisplayName: 'Sodyum adsorpsiyon oranı',
    englishDisplayName: 'Sodium adsorption ratio',
    category: 'DERIVED',
    description: 'Catalog entry for laboratory-reported SAR; engine-calculated values live in WaterDerivedIndicator.',
    canonicalUnitCode: 'NONE',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: false,
    isCalculated: true,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 200,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'ADJUSTED_SAR',
    canonicalName: 'Adjusted sodium adsorption ratio',
    turkishDisplayName: 'Düzeltilmiş SAR',
    englishDisplayName: 'Adjusted SAR',
    category: 'DERIVED',
    description: null,
    canonicalUnitCode: 'NONE',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: false,
    isCalculated: true,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 210,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'RSC',
    canonicalName: 'Residual sodium carbonate',
    turkishDisplayName: 'Kalıntı sodyum karbonat',
    englishDisplayName: 'Residual sodium carbonate',
    category: 'DERIVED',
    description: null,
    canonicalUnitCode: 'MEQ_PER_L',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: false,
    isCalculated: true,
    isRequiredForIrrigationAssessment: true,
    displayOrder: 220,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'TOTAL_HARDNESS',
    canonicalName: 'Total hardness',
    turkishDisplayName: 'Toplam sertlik',
    englishDisplayName: 'Total hardness',
    category: 'DERIVED',
    description: null,
    canonicalUnitCode: 'MG_PER_L_CACO3',
    dataType: 'Decimal',
    decimalPrecision: 1,
    isDirectlyMeasured: false,
    isCalculated: true,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 230,
    source: null,
    verificationStatus: 'Draft',
  },
  {
    code: 'SODIUM_PERCENTAGE',
    canonicalName: 'Sodium percentage',
    turkishDisplayName: 'Sodyum yüzdesi',
    englishDisplayName: 'Sodium percentage',
    category: 'DERIVED',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 2,
    isDirectlyMeasured: false,
    isCalculated: true,
    isRequiredForIrrigationAssessment: false,
    displayOrder: 240,
    source: null,
    verificationStatus: 'Draft',
  },
] as const;

export function waterParameterIdForCode(code: string): string {
  return catalogUuid('water-parameter', code);
}

export function buildWaterParameter(def: WaterParameterSeedDef, now: string): WaterParameter {
  return {
    id: waterParameterIdForCode(def.code),
    code: def.code,
    canonicalName: def.canonicalName,
    turkishDisplayName: def.turkishDisplayName,
    englishDisplayName: def.englishDisplayName,
    category: def.category,
    description: def.description,
    canonicalUnitId: def.canonicalUnitCode ? unitIdForCode(def.canonicalUnitCode) : null,
    dataType: def.dataType,
    decimalPrecision: def.decimalPrecision,
    isDirectlyMeasured: def.isDirectlyMeasured,
    isCalculated: def.isCalculated,
    isRequiredForIrrigationAssessment: def.isRequiredForIrrigationAssessment,
    displayOrder: def.displayOrder,
    source: def.source,
    verificationStatus: def.verificationStatus,
    createdAt: now,
    updatedAt: now,
    version: 1,
    isActive: true,
  };
}
