import type {
  SoilParameter,
  SoilParameterCategory,
  SoilParameterDataType,
  SoilParameterSubCategory,
  SoilParameterUnit,
  SoilParameterValueType,
  SoilMeasurementScope,
} from '../types/soil-parameter.types.js';
import { catalogUuid } from './catalog-ids.js';
import { unitIdForCode } from './measurement-unit.catalog.js';

export type SoilParameterSeedDef = {
  code: string;
  canonicalName: string;
  turkishDisplayName: string;
  englishDisplayName: string;
  category: SoilParameterCategory;
  subCategory: SoilParameterSubCategory | null;
  description: string | null;
  canonicalUnitCode: string;
  dataType: SoilParameterDataType;
  decimalPrecision: number | null;
  valueType: SoilParameterValueType;
  measurementScope: SoilMeasurementScope;
  isDirectlyMeasured: boolean;
  isCalculated: boolean;
  isFieldObservation: boolean;
  isLaboratoryParameter: boolean;
  isRequiredForPhysicalSuitability: boolean;
  isRequiredForFertilityAssessment: boolean;
  displayOrder: number;
  /** Extra allowed import unit codes (canonical always included). */
  allowedImportUnitCodes?: readonly string[];
  /** Units that exist but require context (no auto convert). */
  contextUnitCodes?: readonly string[];
};

function p(
  partial: Omit<SoilParameterSeedDef, 'measurementScope'> & {
    measurementScope?: SoilMeasurementScope;
  },
): SoilParameterSeedDef {
  return {
    measurementScope: 'SAMPLE',
    ...partial,
  };
}

/** Central parameter catalog — codes only; no scientific ranges/thresholds. */
export const SOIL_PARAMETER_SEED: readonly SoilParameterSeedDef[] = [
  // A. Chemical
  p({
    code: 'SOIL_PH',
    canonicalName: 'Soil pH',
    turkishDisplayName: 'Toprak pH',
    englishDisplayName: 'Soil pH',
    category: 'Chemical',
    subCategory: 'AciditySalinity',
    description: 'Soil reaction (pH). Interpretation ranges deferred.',
    canonicalUnitCode: 'PH_UNIT',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'NUMERIC',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 10,
  }),
  p({
    code: 'SOIL_EC',
    canonicalName: 'Electrical conductivity',
    turkishDisplayName: 'Elektriksel iletkenlik',
    englishDisplayName: 'Electrical conductivity',
    category: 'Chemical',
    subCategory: 'AciditySalinity',
    description: 'Soil EC. Canonical unit dS/m; mS/cm accepted (1:1).',
    canonicalUnitCode: 'DS_PER_M',
    dataType: 'Decimal',
    decimalPrecision: 3,
    valueType: 'NUMERIC',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 20,
    allowedImportUnitCodes: ['MS_PER_CM'],
  }),
  p({
    code: 'ORGANIC_MATTER',
    canonicalName: 'Organic matter',
    turkishDisplayName: 'Organik madde',
    englishDisplayName: 'Organic matter',
    category: 'Chemical',
    subCategory: 'OrganicMatter',
    description: 'Soil organic matter. g/kg mapping requires context — not auto-converted.',
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 30,
    contextUnitCodes: ['G_PER_KG'],
  }),
  p({
    code: 'ORGANIC_CARBON',
    canonicalName: 'Organic carbon',
    turkishDisplayName: 'Organik karbon',
    englishDisplayName: 'Organic carbon',
    category: 'Chemical',
    subCategory: 'OrganicMatter',
    description: 'Soil organic carbon. Conversion factors deferred.',
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 40,
    contextUnitCodes: ['G_PER_KG'],
  }),
  p({
    code: 'TOTAL_LIME',
    canonicalName: 'Total lime (CaCO₃)',
    turkishDisplayName: 'Toplam kireç',
    englishDisplayName: 'Total lime',
    category: 'Chemical',
    subCategory: 'AciditySalinity',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 50,
  }),
  p({
    code: 'ACTIVE_LIME',
    canonicalName: 'Active lime',
    turkishDisplayName: 'Aktif kireç',
    englishDisplayName: 'Active lime',
    category: 'Chemical',
    subCategory: 'AciditySalinity',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: false,
    isRequiredForFertilityAssessment: true,
    displayOrder: 60,
  }),
  p({
    code: 'CEC',
    canonicalName: 'Cation exchange capacity',
    turkishDisplayName: 'Katyon değişim kapasitesi',
    englishDisplayName: 'Cation exchange capacity',
    category: 'Chemical',
    subCategory: 'CationExchange',
    description: 'CEC. meq/100g ↔ cmol/kg treated as 1:1.',
    canonicalUnitCode: 'CMOL_PER_KG',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'NUMERIC',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 70,
    allowedImportUnitCodes: ['MEQ_PER_100G'],
  }),
  p({
    code: 'ESP',
    canonicalName: 'Exchangeable sodium percentage',
    turkishDisplayName: 'Değişebilir sodyum yüzdesi',
    englishDisplayName: 'Exchangeable sodium percentage',
    category: 'Chemical',
    subCategory: 'CationExchange',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: false,
    isCalculated: true,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 80,
  }),
  p({
    code: 'SAR_SOIL',
    canonicalName: 'Sodium adsorption ratio (soil)',
    turkishDisplayName: 'Sodyum adsorpsiyon oranı',
    englishDisplayName: 'Sodium adsorption ratio',
    category: 'Chemical',
    subCategory: 'CationExchange',
    description: 'Dimensionless ratio.',
    canonicalUnitCode: 'NONE',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'RATIO',
    isDirectlyMeasured: false,
    isCalculated: true,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 90,
  }),
  p({
    code: 'TOTAL_SALT',
    canonicalName: 'Total salt',
    turkishDisplayName: 'Toplam tuz',
    englishDisplayName: 'Total salt',
    category: 'Chemical',
    subCategory: 'AciditySalinity',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 3,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: true,
    displayOrder: 100,
  }),

  // B. Texture / physical
  p({
    code: 'SAND',
    canonicalName: 'Sand fraction',
    turkishDisplayName: 'Kum',
    englishDisplayName: 'Sand',
    category: 'Physical',
    subCategory: 'Texture',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 110,
  }),
  p({
    code: 'SILT',
    canonicalName: 'Silt fraction',
    turkishDisplayName: 'Silt',
    englishDisplayName: 'Silt',
    category: 'Physical',
    subCategory: 'Texture',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 120,
  }),
  p({
    code: 'CLAY',
    canonicalName: 'Clay fraction',
    turkishDisplayName: 'Kil',
    englishDisplayName: 'Clay',
    category: 'Physical',
    subCategory: 'Texture',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 130,
  }),
  p({
    code: 'SOIL_TEXTURE_CLASS',
    canonicalName: 'Soil texture class',
    turkishDisplayName: 'Toprak tekstür sınıfı',
    englishDisplayName: 'Soil texture class',
    category: 'Physical',
    subCategory: 'Texture',
    description: 'Enum options infrastructure only — class codes not seeded yet.',
    canonicalUnitCode: 'NONE',
    dataType: 'Enum',
    decimalPrecision: null,
    valueType: 'ENUM',
    isDirectlyMeasured: false,
    isCalculated: true,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 140,
  }),
  p({
    code: 'BULK_DENSITY',
    canonicalName: 'Bulk density',
    turkishDisplayName: 'Hacim ağırlığı',
    englishDisplayName: 'Bulk density',
    category: 'Physical',
    subCategory: 'DensityPorosity',
    description: null,
    canonicalUnitCode: 'G_PER_CM3',
    dataType: 'Decimal',
    decimalPrecision: 3,
    valueType: 'NUMERIC',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 150,
  }),
  p({
    code: 'PARTICLE_DENSITY',
    canonicalName: 'Particle density',
    turkishDisplayName: 'Tane yoğunluğu',
    englishDisplayName: 'Particle density',
    category: 'Physical',
    subCategory: 'DensityPorosity',
    description: null,
    canonicalUnitCode: 'G_PER_CM3',
    dataType: 'Decimal',
    decimalPrecision: 3,
    valueType: 'NUMERIC',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: false,
    isRequiredForFertilityAssessment: false,
    displayOrder: 160,
  }),
  p({
    code: 'TOTAL_POROSITY',
    canonicalName: 'Total porosity',
    turkishDisplayName: 'Toplam porozite',
    englishDisplayName: 'Total porosity',
    category: 'Physical',
    subCategory: 'DensityPorosity',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: false,
    isCalculated: true,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: false,
    isRequiredForFertilityAssessment: false,
    displayOrder: 170,
  }),
  p({
    code: 'COARSE_FRAGMENT_CONTENT',
    canonicalName: 'Coarse fragment content',
    turkishDisplayName: 'Kaba fragman içeriği',
    englishDisplayName: 'Coarse fragment content',
    category: 'Physical',
    subCategory: 'Fragments',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: true,
    isLaboratoryParameter: false,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 180,
  }),
  p({
    code: 'GRAVEL_CONTENT',
    canonicalName: 'Gravel content',
    turkishDisplayName: 'Çakıl içeriği',
    englishDisplayName: 'Gravel content',
    category: 'Physical',
    subCategory: 'Fragments',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: true,
    isLaboratoryParameter: false,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 190,
  }),
  p({
    code: 'STONE_CONTENT',
    canonicalName: 'Stone content',
    turkishDisplayName: 'Taş içeriği',
    englishDisplayName: 'Stone content',
    category: 'Physical',
    subCategory: 'Fragments',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: true,
    isLaboratoryParameter: false,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 200,
  }),
  p({
    code: 'SOIL_DEPTH',
    canonicalName: 'Soil depth',
    turkishDisplayName: 'Toprak derinliği',
    englishDisplayName: 'Soil depth',
    category: 'Physical',
    subCategory: 'Depth',
    description: null,
    canonicalUnitCode: 'CM',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'NUMERIC',
    measurementScope: 'PROFILE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: true,
    isLaboratoryParameter: false,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 210,
    allowedImportUnitCodes: ['MM'],
  }),
  p({
    code: 'EFFECTIVE_ROOTING_DEPTH',
    canonicalName: 'Effective rooting depth',
    turkishDisplayName: 'Etkili kök derinliği',
    englishDisplayName: 'Effective rooting depth',
    category: 'Physical',
    subCategory: 'Depth',
    description: null,
    canonicalUnitCode: 'CM',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'NUMERIC',
    measurementScope: 'PROFILE',
    isDirectlyMeasured: false,
    isCalculated: true,
    isFieldObservation: true,
    isLaboratoryParameter: false,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 220,
    allowedImportUnitCodes: ['MM'],
  }),

  // C. Water / moisture
  p({
    code: 'FIELD_CAPACITY',
    canonicalName: 'Field capacity',
    turkishDisplayName: 'Tarla kapasitesi',
    englishDisplayName: 'Field capacity',
    category: 'Hydrological',
    subCategory: 'WaterRetention',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 230,
  }),
  p({
    code: 'PERMANENT_WILTING_POINT',
    canonicalName: 'Permanent wilting point',
    turkishDisplayName: 'Solma noktası',
    englishDisplayName: 'Permanent wilting point',
    category: 'Hydrological',
    subCategory: 'WaterRetention',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 240,
  }),
  p({
    code: 'AVAILABLE_WATER_CAPACITY',
    canonicalName: 'Available water capacity',
    turkishDisplayName: 'Kullanılabilir su kapasitesi',
    englishDisplayName: 'Available water capacity',
    category: 'Hydrological',
    subCategory: 'WaterRetention',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: false,
    isCalculated: true,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 250,
  }),
  p({
    code: 'SATURATION_PERCENTAGE',
    canonicalName: 'Saturation percentage',
    turkishDisplayName: 'Doygunluk yüzdesi',
    englishDisplayName: 'Saturation percentage',
    category: 'Hydrological',
    subCategory: 'WaterRetention',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: false,
    isRequiredForFertilityAssessment: false,
    displayOrder: 260,
  }),
  p({
    code: 'SOIL_MOISTURE',
    canonicalName: 'Soil moisture',
    turkishDisplayName: 'Toprak nemi',
    englishDisplayName: 'Soil moisture',
    category: 'Hydrological',
    subCategory: 'WaterRetention',
    description: null,
    canonicalUnitCode: 'PERCENT',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'PERCENTAGE',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: true,
    isLaboratoryParameter: false,
    isRequiredForPhysicalSuitability: false,
    isRequiredForFertilityAssessment: false,
    displayOrder: 270,
  }),
  p({
    code: 'INFILTRATION_RATE',
    canonicalName: 'Infiltration rate',
    turkishDisplayName: 'İnfiltrasyon hızı',
    englishDisplayName: 'Infiltration rate',
    category: 'Hydrological',
    subCategory: 'Hydraulic',
    description: null,
    canonicalUnitCode: 'MM_PER_HOUR',
    dataType: 'Decimal',
    decimalPrecision: 2,
    valueType: 'NUMERIC',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: true,
    isLaboratoryParameter: false,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 280,
    allowedImportUnitCodes: ['CM_PER_HOUR'],
  }),
  p({
    code: 'HYDRAULIC_CONDUCTIVITY',
    canonicalName: 'Hydraulic conductivity',
    turkishDisplayName: 'Hidrolik iletkenlik',
    englishDisplayName: 'Hydraulic conductivity',
    category: 'Hydrological',
    subCategory: 'Hydraulic',
    description: null,
    canonicalUnitCode: 'CM_PER_HOUR',
    dataType: 'Decimal',
    decimalPrecision: 3,
    valueType: 'NUMERIC',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: false,
    isLaboratoryParameter: true,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 290,
    allowedImportUnitCodes: ['MM_PER_HOUR'],
  }),

  // D. Field observation
  ...[
    ['DRAINAGE_CLASS', 'Drainage class', 'Drenaj sınıfı', 'Drainage class', 300],
    ['COMPACTION_CLASS', 'Compaction class', 'Sıkışma sınıfı', 'Compaction class', 310],
    ['HARDPAN_PRESENCE', 'Hardpan presence', 'Sert tabaka varlığı', 'Hardpan presence', 320],
    ['PONDING_RISK', 'Ponding risk', 'Göllenme riski', 'Ponding risk', 330],
    ['SURFACE_CRUSTING', 'Surface crusting', 'Yüzey kabuklanması', 'Surface crusting', 340],
    ['ROCK_OUTCROP', 'Rock outcrop', 'Kaya çıkıntısı', 'Rock outcrop', 350],
    ['EROSION_CLASS', 'Erosion class', 'Erozyon sınıfı', 'Erosion class', 360],
    ['SALINITY_CRUST', 'Salinity crust', 'Tuz kabuğu', 'Salinity crust', 370],
  ].map(([code, canonical, tr, en, order]) =>
    p({
      code: String(code),
      canonicalName: String(canonical),
      turkishDisplayName: String(tr),
      englishDisplayName: String(en),
      category: 'FieldObservation',
      subCategory: code === 'EROSION_CLASS' || code === 'SALINITY_CRUST'
        ? 'SurfaceCondition'
        : 'DrainageStructure',
      description: 'Enum/classification option codes not scientifically seeded yet.',
      canonicalUnitCode: 'NONE',
      dataType: code === 'HARDPAN_PRESENCE' || code === 'ROCK_OUTCROP' || code === 'SALINITY_CRUST' || code === 'SURFACE_CRUSTING' || code === 'PONDING_RISK'
        ? 'Boolean'
        : 'Enum',
      decimalPrecision: null,
      valueType:
        code === 'HARDPAN_PRESENCE' ||
        code === 'ROCK_OUTCROP' ||
        code === 'SALINITY_CRUST' ||
        code === 'SURFACE_CRUSTING' ||
        code === 'PONDING_RISK'
          ? 'BOOLEAN'
          : 'ENUM',
      measurementScope: 'PARCEL',
      isDirectlyMeasured: false,
      isCalculated: false,
      isFieldObservation: true,
      isLaboratoryParameter: false,
      isRequiredForPhysicalSuitability: true,
      isRequiredForFertilityAssessment: false,
      displayOrder: Number(order),
    }),
  ),
  p({
    code: 'WATER_TABLE_DEPTH',
    canonicalName: 'Water table depth',
    turkishDisplayName: 'Taban suyu derinliği',
    englishDisplayName: 'Water table depth',
    category: 'FieldObservation',
    subCategory: 'Depth',
    description: null,
    canonicalUnitCode: 'CM',
    dataType: 'Decimal',
    decimalPrecision: 1,
    valueType: 'NUMERIC',
    measurementScope: 'PARCEL',
    isDirectlyMeasured: true,
    isCalculated: false,
    isFieldObservation: true,
    isLaboratoryParameter: false,
    isRequiredForPhysicalSuitability: true,
    isRequiredForFertilityAssessment: false,
    displayOrder: 380,
    allowedImportUnitCodes: ['MM'],
  }),

  // E. Nutrients — catalogued but not required for physical suitability
  ...[
    ['TOTAL_NITROGEN', 'Total nitrogen', 'Toplam azot', 'Total nitrogen', 'PERCENT', 'Macronutrient', 400],
    ['AVAILABLE_PHOSPHORUS', 'Available phosphorus', 'Yarayışlı fosfor', 'Available phosphorus', 'MG_PER_KG', 'Macronutrient', 410],
    ['EXCHANGEABLE_POTASSIUM', 'Exchangeable potassium', 'Değişebilir potasyum', 'Exchangeable potassium', 'MG_PER_KG', 'Macronutrient', 420],
    ['CALCIUM', 'Calcium', 'Kalsiyum', 'Calcium', 'MG_PER_KG', 'Macronutrient', 430],
    ['MAGNESIUM', 'Magnesium', 'Magnezyum', 'Magnesium', 'MG_PER_KG', 'Macronutrient', 440],
    ['SULFUR', 'Sulfur', 'Kükürt', 'Sulfur', 'MG_PER_KG', 'Macronutrient', 450],
    ['IRON', 'Iron', 'Demir', 'Iron', 'MG_PER_KG', 'Micronutrient', 460],
    ['ZINC', 'Zinc', 'Çinko', 'Zinc', 'MG_PER_KG', 'Micronutrient', 470],
    ['COPPER', 'Copper', 'Bakır', 'Copper', 'MG_PER_KG', 'Micronutrient', 480],
    ['MANGANESE', 'Manganese', 'Mangan', 'Manganese', 'MG_PER_KG', 'Micronutrient', 490],
    ['BORON', 'Boron', 'Bor', 'Boron', 'MG_PER_KG', 'Micronutrient', 500],
  ].map(([code, canonical, tr, en, unit, sub, order]) =>
    p({
      code: String(code),
      canonicalName: String(canonical),
      turkishDisplayName: String(tr),
      englishDisplayName: String(en),
      category: 'Nutrient',
      subCategory: sub as SoilParameterSubCategory,
      description: 'Nutrient catalog entry; physical suitability requirement flag is false.',
      canonicalUnitCode: String(unit),
      dataType: 'Decimal',
      decimalPrecision: 2,
      valueType: unit === 'PERCENT' ? 'PERCENTAGE' : 'NUMERIC',
      isDirectlyMeasured: true,
      isCalculated: false,
      isFieldObservation: false,
      isLaboratoryParameter: true,
      isRequiredForPhysicalSuitability: false,
      isRequiredForFertilityAssessment: true,
      displayOrder: Number(order),
    }),
  ),
] as const;

/** Parameters that will host SoilParameterOption rows later (infra only in 2.2C). */
export const ENUM_OPTION_INFRASTRUCTURE_CODES = [
  'SOIL_TEXTURE_CLASS',
  'DRAINAGE_CLASS',
  'COMPACTION_CLASS',
  'EROSION_CLASS',
  'HARDPAN_PRESENCE',
  'ROCK_OUTCROP',
] as const;

export function parameterIdForCode(code: string): string {
  return catalogUuid('soil-parameter', code);
}

export function parameterUnitMappingId(parameterCode: string, unitCode: string): string {
  return catalogUuid('soil-parameter-unit', `${parameterCode}:${unitCode}`);
}

export function resolveCanonicalUnitId(unitCode: string): string {
  return unitIdForCode(unitCode);
}

export function buildSoilParameter(def: SoilParameterSeedDef, now: string): SoilParameter {
  return {
    id: parameterIdForCode(def.code),
    code: def.code,
    canonicalName: def.canonicalName,
    turkishDisplayName: def.turkishDisplayName,
    englishDisplayName: def.englishDisplayName,
    category: def.category,
    subCategory: def.subCategory,
    description: def.description,
    canonicalUnitId: unitIdForCode(def.canonicalUnitCode),
    dataType: def.dataType,
    decimalPrecision: def.decimalPrecision,
    valueType: def.valueType,
    measurementScope: def.measurementScope,
    isDirectlyMeasured: def.isDirectlyMeasured,
    isCalculated: def.isCalculated,
    isFieldObservation: def.isFieldObservation,
    isLaboratoryParameter: def.isLaboratoryParameter,
    isRequiredForPhysicalSuitability: def.isRequiredForPhysicalSuitability,
    isRequiredForFertilityAssessment: def.isRequiredForFertilityAssessment,
    displayOrder: def.displayOrder,
    source: null,
    verificationStatus: 'Draft',
    createdAt: now,
    updatedAt: now,
    version: 1,
    isActive: true,
  };
}

export function buildParameterUnitMappings(
  def: SoilParameterSeedDef,
  now: string,
): SoilParameterUnit[] {
  const parameterId = parameterIdForCode(def.code);
  const codes = new Set<string>([
    def.canonicalUnitCode,
    ...(def.allowedImportUnitCodes ?? []),
    ...(def.contextUnitCodes ?? []),
  ]);
  const rows: SoilParameterUnit[] = [];
  for (const unitCode of codes) {
    const isCanonical = unitCode === def.canonicalUnitCode;
    const requiresContext = (def.contextUnitCodes ?? []).includes(unitCode);
    rows.push({
      id: parameterUnitMappingId(def.code, unitCode),
      parameterId,
      unitId: unitIdForCode(unitCode),
      isCanonical,
      isAllowedForImport: true,
      requiresContext,
      conversionNotes: requiresContext
        ? 'Context-dependent unit; automatic conversion is unsupported'
        : null,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      version: 1,
    });
  }
  return rows;
}
