import { catalogUuid } from '../../soil-laboratory/catalogs/catalog-ids.js';
import { unitIdForCode } from '../../soil-laboratory/catalogs/measurement-unit.catalog.js';
import type { VerificationStatus } from '../../types/physical-suitability.types.js';
import type {
  AgroClimateIndicator,
  CalculationType,
  Category,
  IndicatorCode,
  SpatialScope,
  TemporalScope,
} from '../types/agroclimate.types.js';

/**
 * Seed catalog — Phase 2.3A AgroClimate Indicators Engine.
 * Exactly 58 indicators across TEMPERATURE, FROST, HEAT, GROWING_SEASON,
 * PRECIPITATION, DROUGHT, WATER_BALANCE, EVAPOTRANSPIRATION, RADIATION,
 * HUMIDITY, WIND and DATA_QUALITY categories.
 *
 * No suitability/interpretation thresholds are seeded (minimumDataCoveragePercent
 * and isRequiredForPhysicalSuitability stay null/false); no crop-specific content
 * of any kind.
 *
 * Unit codes: NONE, PERCENT, MM and DEG_C are already part of the shared
 * measurement-unit catalog (soil-laboratory). DAY, DEG_C_DAY, MM_PER_DAY,
 * M_PER_S, MJ_M2, MJ_M2_DAY, HOUR, KPA and DEG are anticipated additions —
 * `unitIdForCode` is a pure deterministic hash so the ids below are stable and
 * forward compatible even though those units are not yet formally seeded
 * anywhere.
 */

export type AgroClimateIndicatorSeedDef = {
  code: IndicatorCode;
  canonicalName: string;
  turkishDisplayName: string;
  englishDisplayName: string;
  category: Category;
  description: string | null;
  calculationType: CalculationType;
  temporalScope: TemporalScope;
  spatialScope: SpatialScope;
  requiresDailyData: boolean;
  requiresHourlyData: boolean;
  canonicalUnitCode: string | null;
  formulaVersion: string;
  displayOrder: number;
};

export const AGROCLIMATE_INDICATOR_SEED: readonly AgroClimateIndicatorSeedDef[] = [
  // ------------------------------------------------------------ TEMPERATURE --
  {
    code: 'MEAN_TEMPERATURE',
    canonicalName: 'Mean temperature',
    turkishDisplayName: 'Ortalama sıcaklık',
    englishDisplayName: 'Mean temperature',
    category: 'TEMPERATURE',
    description: 'Arithmetic mean of T2M_MEAN over the analysis period.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG_C',
    formulaVersion: 'MEAN_TEMPERATURE_v1',
    displayOrder: 10,
  },
  {
    code: 'MINIMUM_TEMPERATURE',
    canonicalName: 'Mean minimum temperature',
    turkishDisplayName: 'Ortalama minimum sıcaklık',
    englishDisplayName: 'Mean minimum temperature',
    category: 'TEMPERATURE',
    description: 'Arithmetic mean of T2M_MIN over the analysis period.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG_C',
    formulaVersion: 'MINIMUM_TEMPERATURE_v1',
    displayOrder: 20,
  },
  {
    code: 'MAXIMUM_TEMPERATURE',
    canonicalName: 'Mean maximum temperature',
    turkishDisplayName: 'Ortalama maksimum sıcaklık',
    englishDisplayName: 'Mean maximum temperature',
    category: 'TEMPERATURE',
    description: 'Arithmetic mean of T2M_MAX over the analysis period.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG_C',
    formulaVersion: 'MAXIMUM_TEMPERATURE_v1',
    displayOrder: 30,
  },
  {
    code: 'TEMPERATURE_RANGE',
    canonicalName: 'Diurnal temperature range',
    turkishDisplayName: 'Günlük sıcaklık farkı',
    englishDisplayName: 'Diurnal temperature range',
    category: 'TEMPERATURE',
    description: 'Mean of (T2M_MAX − T2M_MIN) over the analysis period.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG_C',
    formulaVersion: 'TEMPERATURE_RANGE_v1',
    displayOrder: 40,
  },
  {
    code: 'MEAN_GROWING_SEASON_TEMPERATURE',
    canonicalName: 'Mean growing season temperature',
    turkishDisplayName: 'Ortalama yetişme mevsimi sıcaklığı',
    englishDisplayName: 'Mean growing season temperature',
    category: 'TEMPERATURE',
    description:
      'Mean T2M_MEAN restricted to the thermal growing season. Depends on GROWING_SEASON_START_DATE / GROWING_SEASON_END_DATE, which are not yet implemented in Phase 2.3A.',
    calculationType: 'AGGREGATED',
    temporalScope: 'SEASONAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG_C',
    formulaVersion: 'MEAN_GROWING_SEASON_TEMPERATURE_v1',
    displayOrder: 50,
  },
  // ---------------------------------------------------------------- FROST --
  {
    code: 'FROST_DAY_COUNT',
    canonicalName: 'Frost day count',
    turkishDisplayName: 'Don günü sayısı',
    englishDisplayName: 'Frost day count',
    category: 'FROST',
    description: 'Count of days with T2M_MIN at or below the configured frost threshold.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'FROST_DAY_COUNT_v1',
    displayOrder: 60,
  },
  {
    code: 'SEVERE_FROST_DAY_COUNT',
    canonicalName: 'Severe frost day count',
    turkishDisplayName: 'Şiddetli don günü sayısı',
    englishDisplayName: 'Severe frost day count',
    category: 'FROST',
    description: 'Count of days with T2M_MIN at or below the configured severe-frost threshold.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'SEVERE_FROST_DAY_COUNT_v1',
    displayOrder: 70,
  },
  {
    code: 'LAST_SPRING_FROST_DATE',
    canonicalName: 'Last spring frost date',
    turkishDisplayName: 'Son ilkbahar donu tarihi',
    englishDisplayName: 'Last spring frost date',
    category: 'FROST',
    description: 'Latest frost day at or before the mid-point of the analysis period.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'ANNUAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: null,
    formulaVersion: 'LAST_SPRING_FROST_DATE_v1',
    displayOrder: 80,
  },
  {
    code: 'FIRST_AUTUMN_FROST_DATE',
    canonicalName: 'First autumn frost date',
    turkishDisplayName: 'İlk sonbahar donu tarihi',
    englishDisplayName: 'First autumn frost date',
    category: 'FROST',
    description: 'Earliest frost day after the mid-point of the analysis period.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'ANNUAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: null,
    formulaVersion: 'FIRST_AUTUMN_FROST_DATE_v1',
    displayOrder: 90,
  },
  {
    code: 'FROST_FREE_PERIOD_DAYS',
    canonicalName: 'Frost-free period length',
    turkishDisplayName: 'Donsuz dönem uzunluğu',
    englishDisplayName: 'Frost-free period length',
    category: 'FROST',
    description: 'Days between the last spring frost and the first autumn frost.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'ANNUAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'FROST_FREE_PERIOD_DAYS_v1',
    displayOrder: 100,
  },
  {
    code: 'FROST_EVENT_COUNT',
    canonicalName: 'Frost event count',
    turkishDisplayName: 'Don olayı sayısı',
    englishDisplayName: 'Frost event count',
    category: 'FROST',
    description: 'Count of distinct runs of one or more consecutive frost days.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'FROST_EVENT_COUNT_v1',
    displayOrder: 110,
  },
  {
    code: 'LONGEST_FROST_EVENT_DAYS',
    canonicalName: 'Longest consecutive frost run',
    turkishDisplayName: 'En uzun ardışık don süresi',
    englishDisplayName: 'Longest consecutive frost run',
    category: 'FROST',
    description: 'Longest run of consecutive frost days in the analysis period.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'LONGEST_FROST_EVENT_DAYS_v1',
    displayOrder: 120,
  },
  // ----------------------------------------------------------------- HEAT --
  {
    code: 'EXTREME_HEAT_DAY_COUNT',
    canonicalName: 'Extreme heat day count',
    turkishDisplayName: 'Aşırı sıcak gün sayısı',
    englishDisplayName: 'Extreme heat day count',
    category: 'HEAT',
    description: 'Count of days with T2M_MAX at or above the configured extreme-heat threshold.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'EXTREME_HEAT_DAY_COUNT_v1',
    displayOrder: 130,
  },
  {
    code: 'HEATWAVE_EVENT_COUNT',
    canonicalName: 'Heatwave event count',
    turkishDisplayName: 'Sıcak hava dalgası olay sayısı',
    englishDisplayName: 'Heatwave event count',
    category: 'HEAT',
    description:
      'Count of extreme-heat runs whose length meets or exceeds the configured minimum heatwave duration.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'HEATWAVE_EVENT_COUNT_v1',
    displayOrder: 140,
  },
  {
    code: 'LONGEST_HEATWAVE_DAYS',
    canonicalName: 'Longest heatwave duration',
    turkishDisplayName: 'En uzun sıcak hava dalgası süresi',
    englishDisplayName: 'Longest heatwave duration',
    category: 'HEAT',
    description: 'Longest qualifying heatwave event in the analysis period.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'LONGEST_HEATWAVE_DAYS_v1',
    displayOrder: 150,
  },
  {
    code: 'MAXIMUM_HEATWAVE_TEMPERATURE',
    canonicalName: 'Maximum heatwave temperature',
    turkishDisplayName: 'Sıcak hava dalgası maksimum sıcaklığı',
    englishDisplayName: 'Maximum heatwave temperature',
    category: 'HEAT',
    description: 'Highest T2M_MAX observed among days belonging to a qualifying heatwave event.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG_C',
    formulaVersion: 'MAXIMUM_HEATWAVE_TEMPERATURE_v1',
    displayOrder: 160,
  },
  {
    code: 'HIGH_NIGHT_TEMPERATURE_COUNT',
    canonicalName: 'High night temperature days count',
    turkishDisplayName: 'Yüksek gece sıcaklığı gün sayısı',
    englishDisplayName: 'High night temperature days count',
    category: 'HEAT',
    description:
      'Count of days with T2M_MIN at or above the night-temperature threshold ("tropical nights").',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'HIGH_NIGHT_TEMPERATURE_COUNT_v1',
    displayOrder: 170,
  },
  // --------------------------------------------------------- GROWING_SEASON --
  {
    code: 'GDD',
    canonicalName: 'Growing degree days',
    turkishDisplayName: 'Büyüme derece günü',
    englishDisplayName: 'Growing degree days',
    category: 'GROWING_SEASON',
    description: 'GDD = max(0, (Tmin+Tmax)/2 − base), accumulated over the analysis period (simple-average method).',
    calculationType: 'DERIVED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG_C_DAY',
    formulaVersion: 'GDD_v1',
    displayOrder: 180,
  },
  {
    code: 'GDD_BASE_TEMPERATURE',
    canonicalName: 'GDD base temperature',
    turkishDisplayName: 'Büyüme derece günü taban sıcaklığı',
    englishDisplayName: 'GDD base temperature',
    category: 'GROWING_SEASON',
    description: 'Configured base temperature used for the GDD calculation, reported for traceability.',
    calculationType: 'DIRECT',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG_C',
    formulaVersion: 'GDD_BASE_TEMPERATURE_v1',
    displayOrder: 190,
  },
  {
    code: 'GROWING_SEASON_START_DATE',
    canonicalName: 'Growing season start date',
    turkishDisplayName: 'Yetişme mevsimi başlangıç tarihi',
    englishDisplayName: 'Growing season start date',
    category: 'GROWING_SEASON',
    description: 'Start-detection rule not defined in Phase 2.3A. Not implemented.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'ANNUAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: null,
    formulaVersion: 'GROWING_SEASON_START_DATE_v1',
    displayOrder: 200,
  },
  {
    code: 'GROWING_SEASON_END_DATE',
    canonicalName: 'Growing season end date',
    turkishDisplayName: 'Yetişme mevsimi bitiş tarihi',
    englishDisplayName: 'Growing season end date',
    category: 'GROWING_SEASON',
    description: 'End-detection rule not defined in Phase 2.3A. Not implemented.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'ANNUAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: null,
    formulaVersion: 'GROWING_SEASON_END_DATE_v1',
    displayOrder: 210,
  },
  {
    code: 'GROWING_SEASON_LENGTH',
    canonicalName: 'Growing season length',
    turkishDisplayName: 'Yetişme mevsimi uzunluğu',
    englishDisplayName: 'Growing season length',
    category: 'GROWING_SEASON',
    description:
      'Length of the thermal growing season. Depends on GROWING_SEASON_START_DATE / GROWING_SEASON_END_DATE, which are not yet implemented in Phase 2.3A.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'ANNUAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'GROWING_SEASON_LENGTH_v1',
    displayOrder: 220,
  },
  {
    code: 'ACTIVE_GROWING_DAY_COUNT',
    canonicalName: 'Active growing day count',
    turkishDisplayName: 'Aktif gelişme günü sayısı',
    englishDisplayName: 'Active growing day count',
    category: 'GROWING_SEASON',
    description: 'Count of days whose simple-average daily GDD contribution is greater than zero.',
    calculationType: 'DERIVED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'ACTIVE_GROWING_DAY_COUNT_v1',
    displayOrder: 230,
  },
  // ----------------------------------------------------------- PRECIPITATION --
  {
    code: 'TOTAL_PRECIPITATION',
    canonicalName: 'Total precipitation',
    turkishDisplayName: 'Toplam yağış',
    englishDisplayName: 'Total precipitation',
    category: 'PRECIPITATION',
    description: 'Sum of known-day PRECIPITATION values over the analysis period.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'TOTAL_PRECIPITATION_v1',
    displayOrder: 240,
  },
  {
    code: 'SEASONAL_PRECIPITATION',
    canonicalName: 'Seasonal precipitation',
    turkishDisplayName: 'Mevsimlik yağış',
    englishDisplayName: 'Seasonal precipitation',
    category: 'PRECIPITATION',
    description: 'Sum of known-day PRECIPITATION values over a seasonal analysis period.',
    calculationType: 'AGGREGATED',
    temporalScope: 'SEASONAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'SEASONAL_PRECIPITATION_v1',
    displayOrder: 250,
  },
  {
    code: 'RAINY_DAY_COUNT',
    canonicalName: 'Rainy day count',
    turkishDisplayName: 'Yağışlı gün sayısı',
    englishDisplayName: 'Rainy day count',
    category: 'PRECIPITATION',
    description: 'Count of days with precipitation at or above the rainy-day threshold.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'RAINY_DAY_COUNT_v1',
    displayOrder: 260,
  },
  {
    code: 'HEAVY_RAIN_DAY_COUNT',
    canonicalName: 'Heavy rain day count',
    turkishDisplayName: 'Şiddetli yağış günü sayısı',
    englishDisplayName: 'Heavy rain day count',
    category: 'PRECIPITATION',
    description: 'Count of days with precipitation at or above the heavy-rain threshold.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'HEAVY_RAIN_DAY_COUNT_v1',
    displayOrder: 270,
  },
  {
    code: 'MAXIMUM_DAILY_PRECIPITATION',
    canonicalName: 'Maximum daily precipitation',
    turkishDisplayName: 'Maksimum günlük yağış',
    englishDisplayName: 'Maximum daily precipitation',
    category: 'PRECIPITATION',
    description: 'Highest single-day precipitation value in the analysis period.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'MAXIMUM_DAILY_PRECIPITATION_v1',
    displayOrder: 280,
  },
  {
    code: 'PRECIPITATION_VARIABILITY',
    canonicalName: 'Precipitation variability',
    turkishDisplayName: 'Yağış değişkenliği',
    englishDisplayName: 'Precipitation variability',
    category: 'PRECIPITATION',
    description: 'Population standard deviation of fully-known calendar-month precipitation totals.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'PRECIPITATION_VARIABILITY_v1',
    displayOrder: 290,
  },
  {
    code: 'PRECIPITATION_CONCENTRATION',
    canonicalName: 'Precipitation concentration index',
    turkishDisplayName: 'Yağış yoğunlaşma indeksi',
    englishDisplayName: 'Precipitation concentration index',
    category: 'PRECIPITATION',
    description: 'PCI computed from fully-known calendar months in the analysis period.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'PRECIPITATION_CONCENTRATION_v1',
    displayOrder: 300,
  },
  // ----------------------------------------------------------------- DROUGHT --
  {
    code: 'CONSECUTIVE_DRY_DAYS',
    canonicalName: 'Consecutive dry days',
    turkishDisplayName: 'Ardışık kurak gün sayısı',
    englishDisplayName: 'Consecutive dry days',
    category: 'DROUGHT',
    description:
      'Longest run of consecutive dry days in the analysis period (CDD-style index). Missing days break the run — never counted as dry.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'CONSECUTIVE_DRY_DAYS_v1',
    displayOrder: 310,
  },
  {
    code: 'LONGEST_DRY_SPELL',
    canonicalName: 'Longest dry spell',
    turkishDisplayName: 'En uzun kurak dönem',
    englishDisplayName: 'Longest dry spell',
    category: 'DROUGHT',
    description:
      'Longest individual dry-spell event in the analysis period, reported with its start/end dates. Same underlying duration as CONSECUTIVE_DRY_DAYS, exposed as a discrete event.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'LONGEST_DRY_SPELL_v1',
    displayOrder: 320,
  },
  {
    code: 'DRY_SPELL_EVENT_COUNT',
    canonicalName: 'Dry spell event count',
    turkishDisplayName: 'Kurak dönem olay sayısı',
    englishDisplayName: 'Dry spell event count',
    category: 'DROUGHT',
    description: 'Count of distinct runs of one or more consecutive dry days.',
    calculationType: 'EVENT_BASED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'DRY_SPELL_EVENT_COUNT_v1',
    displayOrder: 330,
  },
  {
    code: 'PRECIPITATION_DEFICIT',
    canonicalName: 'Precipitation deficit',
    turkishDisplayName: 'Yağış açığı',
    englishDisplayName: 'Precipitation deficit',
    category: 'DROUGHT',
    description:
      'Shortfall of analysis-period precipitation relative to the baseline period. Baseline comparison methodology is not defined in Phase 2.3A. Not implemented.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'PRECIPITATION_DEFICIT_v1',
    displayOrder: 340,
  },
  {
    code: 'METEOROLOGICAL_DROUGHT_INDEX',
    canonicalName: 'Meteorological drought index',
    turkishDisplayName: 'Meteorolojik kuraklık indeksi',
    englishDisplayName: 'Meteorological drought index',
    category: 'DROUGHT',
    description:
      'Standardized drought index (e.g. SPI-style). Requires a multi-year climatology baseline not available in Phase 2.3A. Not implemented.',
    calculationType: 'STATISTICAL',
    temporalScope: 'MULTI_YEAR',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'METEOROLOGICAL_DROUGHT_INDEX_v1',
    displayOrder: 350,
  },
  // ---------------------------------------- WATER_BALANCE / EVAPOTRANSPIRATION --
  {
    code: 'REFERENCE_EVAPOTRANSPIRATION',
    canonicalName: 'Reference evapotranspiration total',
    turkishDisplayName: 'Referans evapotranspirasyon toplamı',
    englishDisplayName: 'Reference evapotranspiration total',
    category: 'EVAPOTRANSPIRATION',
    description: 'Sum of reference evapotranspiration (ET0) over the analysis period. No crop coefficient (Kc) applied.',
    calculationType: 'DERIVED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'REFERENCE_EVAPOTRANSPIRATION_v1',
    displayOrder: 360,
  },
  {
    code: 'POTENTIAL_EVAPOTRANSPIRATION',
    canonicalName: 'Potential evapotranspiration daily mean',
    turkishDisplayName: 'Potansiyel evapotranspirasyon günlük ortalaması',
    englishDisplayName: 'Potential evapotranspiration daily mean',
    category: 'EVAPOTRANSPIRATION',
    description: 'Mean daily reference evapotranspiration (ET0) over the analysis period. No crop coefficient (Kc) applied.',
    calculationType: 'DERIVED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM_PER_DAY',
    formulaVersion: 'POTENTIAL_EVAPOTRANSPIRATION_v1',
    displayOrder: 370,
  },
  {
    code: 'CLIMATIC_WATER_DEFICIT',
    canonicalName: 'Climatic water deficit',
    turkishDisplayName: 'İklimsel su açığı',
    englishDisplayName: 'Climatic water deficit',
    category: 'WATER_BALANCE',
    description: 'Sum of max(0, ET0 − precipitation) over daily known pairs. No crop coefficient (Kc) applied.',
    calculationType: 'DERIVED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'CLIMATIC_WATER_DEFICIT_v1',
    displayOrder: 380,
  },
  {
    code: 'CLIMATIC_WATER_SURPLUS',
    canonicalName: 'Climatic water surplus',
    turkishDisplayName: 'İklimsel su fazlası',
    englishDisplayName: 'Climatic water surplus',
    category: 'WATER_BALANCE',
    description: 'Sum of max(0, precipitation − ET0) over daily known pairs. No crop coefficient (Kc) applied.',
    calculationType: 'DERIVED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'CLIMATIC_WATER_SURPLUS_v1',
    displayOrder: 390,
  },
  {
    code: 'PRECIPITATION_ET0_RATIO',
    canonicalName: 'Precipitation to ET0 ratio',
    turkishDisplayName: 'Yağış / ET0 oranı',
    englishDisplayName: 'Precipitation to ET0 ratio',
    category: 'WATER_BALANCE',
    description: 'Ratio of total precipitation to total ET0 over daily known pairs. No classification applied.',
    calculationType: 'DERIVED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'PRECIPITATION_ET0_RATIO_v1',
    displayOrder: 400,
  },
  {
    code: 'SEASONAL_WATER_BALANCE',
    canonicalName: 'Seasonal water balance',
    turkishDisplayName: 'Mevsimlik su bilançosu',
    englishDisplayName: 'Seasonal water balance',
    category: 'WATER_BALANCE',
    description: 'Sum of (precipitation − ET0) over daily known pairs. No crop coefficient (Kc) applied.',
    calculationType: 'DERIVED',
    temporalScope: 'SEASONAL',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'MM',
    formulaVersion: 'SEASONAL_WATER_BALANCE_v1',
    displayOrder: 410,
  },
  // -------------------------------------------------------------- RADIATION --
  {
    code: 'TOTAL_SOLAR_RADIATION',
    canonicalName: 'Total solar radiation',
    turkishDisplayName: 'Toplam güneş radyasyonu',
    englishDisplayName: 'Total solar radiation',
    category: 'RADIATION',
    description: 'Sum of SOLAR_RADIATION over the analysis period. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'MJ_M2',
    formulaVersion: 'TOTAL_SOLAR_RADIATION_v1',
    displayOrder: 420,
  },
  {
    code: 'MEAN_DAILY_SOLAR_RADIATION',
    canonicalName: 'Mean daily solar radiation',
    turkishDisplayName: 'Ortalama günlük güneş radyasyonu',
    englishDisplayName: 'Mean daily solar radiation',
    category: 'RADIATION',
    description: 'Arithmetic mean of SOLAR_RADIATION over the analysis period. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'MJ_M2_DAY',
    formulaVersion: 'MEAN_DAILY_SOLAR_RADIATION_v1',
    displayOrder: 430,
  },
  {
    code: 'SUNSHINE_DURATION',
    canonicalName: 'Total sunshine duration',
    turkishDisplayName: 'Toplam güneşlenme süresi',
    englishDisplayName: 'Total sunshine duration',
    category: 'RADIATION',
    description: 'Sum of daily sunshine duration over the analysis period. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'HOUR',
    formulaVersion: 'SUNSHINE_DURATION_v1',
    displayOrder: 440,
  },
  {
    code: 'LOW_RADIATION_DAY_COUNT',
    canonicalName: 'Low radiation day count',
    turkishDisplayName: 'Düşük radyasyon günü sayısı',
    englishDisplayName: 'Low radiation day count',
    category: 'RADIATION',
    description: 'Count of days at or below the low-radiation threshold. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'LOW_RADIATION_DAY_COUNT_v1',
    displayOrder: 450,
  },
  // --------------------------------------------------------------- HUMIDITY --
  {
    code: 'MEAN_RELATIVE_HUMIDITY',
    canonicalName: 'Mean relative humidity',
    turkishDisplayName: 'Ortalama bağıl nem',
    englishDisplayName: 'Mean relative humidity',
    category: 'HUMIDITY',
    description: 'Arithmetic mean of RELATIVE_HUMIDITY over the analysis period. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'PERCENT',
    formulaVersion: 'MEAN_RELATIVE_HUMIDITY_v1',
    displayOrder: 460,
  },
  {
    code: 'LOW_HUMIDITY_DAY_COUNT',
    canonicalName: 'Low humidity day count',
    turkishDisplayName: 'Düşük nem günü sayısı',
    englishDisplayName: 'Low humidity day count',
    category: 'HUMIDITY',
    description: 'Count of days at or below the low-humidity threshold. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'LOW_HUMIDITY_DAY_COUNT_v1',
    displayOrder: 470,
  },
  {
    code: 'HIGH_HUMIDITY_DAY_COUNT',
    canonicalName: 'High humidity day count',
    turkishDisplayName: 'Yüksek nem günü sayısı',
    englishDisplayName: 'High humidity day count',
    category: 'HUMIDITY',
    description: 'Count of days at or above the high-humidity threshold. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'HIGH_HUMIDITY_DAY_COUNT_v1',
    displayOrder: 480,
  },
  {
    code: 'VAPOR_PRESSURE_DEFICIT',
    canonicalName: 'Mean vapor pressure deficit',
    turkishDisplayName: 'Ortalama buhar basıncı açığı',
    englishDisplayName: 'Mean vapor pressure deficit',
    category: 'HUMIDITY',
    description: 'Mean VPD derived from T2M_MEAN and RELATIVE_HUMIDITY. Calculation engine not yet implemented.',
    calculationType: 'DERIVED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'KPA',
    formulaVersion: 'VAPOR_PRESSURE_DEFICIT_v1',
    displayOrder: 490,
  },
  // ------------------------------------------------------------------ WIND --
  {
    code: 'MEAN_WIND_SPEED',
    canonicalName: 'Mean wind speed',
    turkishDisplayName: 'Ortalama rüzgar hızı',
    englishDisplayName: 'Mean wind speed',
    category: 'WIND',
    description: 'Arithmetic mean of WIND_SPEED over the analysis period. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'M_PER_S',
    formulaVersion: 'MEAN_WIND_SPEED_v1',
    displayOrder: 500,
  },
  {
    code: 'MAXIMUM_WIND_SPEED',
    canonicalName: 'Maximum wind speed',
    turkishDisplayName: 'Maksimum rüzgar hızı',
    englishDisplayName: 'Maximum wind speed',
    category: 'WIND',
    description: 'Highest WIND_SPEED observed in the analysis period. Calculation engine not yet implemented.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'M_PER_S',
    formulaVersion: 'MAXIMUM_WIND_SPEED_v1',
    displayOrder: 510,
  },
  {
    code: 'HIGH_WIND_DAY_COUNT',
    canonicalName: 'High wind day count',
    turkishDisplayName: 'Yüksek rüzgar günü sayısı',
    englishDisplayName: 'High wind day count',
    category: 'WIND',
    description: 'Count of days at or above the high-wind threshold. Calculation engine not yet implemented.',
    calculationType: 'AGGREGATED',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'HIGH_WIND_DAY_COUNT_v1',
    displayOrder: 520,
  },
  {
    code: 'PREVAILING_WIND_DIRECTION',
    canonicalName: 'Prevailing wind direction',
    turkishDisplayName: 'Hakim rüzgar yönü',
    englishDisplayName: 'Prevailing wind direction',
    category: 'WIND',
    description: 'Most frequent WIND_DIRECTION sector over the analysis period. Calculation engine not yet implemented.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: true,
    requiresHourlyData: false,
    canonicalUnitCode: 'DEG',
    formulaVersion: 'PREVAILING_WIND_DIRECTION_v1',
    displayOrder: 530,
  },
  // -------------------------------------------------------------- DATA_QUALITY --
  {
    code: 'DATA_COVERAGE_PERCENT',
    canonicalName: 'Data coverage percent',
    turkishDisplayName: 'Veri kapsama yüzdesi',
    englishDisplayName: 'Data coverage percent',
    category: 'DATA_QUALITY',
    description: 'Share of expected observation days that are actually present, across all parameters used by the run.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'PERCENT',
    formulaVersion: 'DATA_COVERAGE_PERCENT_v1',
    displayOrder: 540,
  },
  {
    code: 'MISSING_DAY_COUNT',
    canonicalName: 'Missing day count',
    turkishDisplayName: 'Eksik gün sayısı',
    englishDisplayName: 'Missing day count',
    category: 'DATA_QUALITY',
    description: 'Count of expected observation days with no known value, across all parameters used by the run.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'DAY',
    formulaVersion: 'MISSING_DAY_COUNT_v1',
    displayOrder: 550,
  },
  {
    code: 'SOURCE_CONSISTENCY_SCORE',
    canonicalName: 'Source consistency score',
    turkishDisplayName: 'Kaynak tutarlılık skoru',
    englishDisplayName: 'Source consistency score',
    category: 'DATA_QUALITY',
    description:
      'Summary score derived from ClimateSourceComparison statistics. No scoring formula is defined in Phase 2.3A. Not implemented.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'SOURCE_CONSISTENCY_SCORE_v1',
    displayOrder: 560,
  },
  {
    code: 'OUTLIER_COUNT',
    canonicalName: 'Outlier count',
    turkishDisplayName: 'Aykırı değer sayısı',
    englishDisplayName: 'Outlier count',
    category: 'DATA_QUALITY',
    description: 'Count of observations flagged as statistical outliers. Outlier-detection rule not defined in Phase 2.3A. Not implemented.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'OUTLIER_COUNT_v1',
    displayOrder: 570,
  },
  {
    code: 'QUALITY_SCORE',
    canonicalName: 'Overall quality score',
    turkishDisplayName: 'Genel kalite skoru',
    englishDisplayName: 'Overall quality score',
    category: 'DATA_QUALITY',
    description:
      'Composite score summarizing coverage, consistency and outlier signals for the run. No scoring formula is defined in Phase 2.3A. Not implemented.',
    calculationType: 'STATISTICAL',
    temporalScope: 'CUSTOM_PERIOD',
    spatialScope: 'PARCEL',
    requiresDailyData: false,
    requiresHourlyData: false,
    canonicalUnitCode: 'NONE',
    formulaVersion: 'QUALITY_SCORE_v1',
    displayOrder: 580,
  },
] as const;

const DEFAULT_VERIFICATION_STATUS: VerificationStatus = 'Draft';

export function agroClimateIndicatorIdForCode(code: IndicatorCode): string {
  return catalogUuid('agroclimate-indicator', code);
}

export function buildAgroClimateIndicator(
  def: AgroClimateIndicatorSeedDef,
  now: string,
): AgroClimateIndicator {
  return {
    id: agroClimateIndicatorIdForCode(def.code),
    code: def.code,
    canonicalName: def.canonicalName,
    turkishDisplayName: def.turkishDisplayName,
    englishDisplayName: def.englishDisplayName,
    category: def.category,
    description: def.description,
    canonicalUnitId: def.canonicalUnitCode ? unitIdForCode(def.canonicalUnitCode) : null,
    calculationType: def.calculationType,
    temporalScope: def.temporalScope,
    spatialScope: def.spatialScope,
    requiresDailyData: def.requiresDailyData,
    requiresHourlyData: def.requiresHourlyData,
    minimumDataCoveragePercent: null,
    formulaVersion: def.formulaVersion,
    isRequiredForPhysicalSuitability: false,
    displayOrder: def.displayOrder,
    source: null,
    verificationStatus: DEFAULT_VERIFICATION_STATUS,
    createdAt: now,
    updatedAt: now,
    version: 1,
    isActive: true,
  };
}

export function buildAgroClimateIndicatorCatalog(now: string): AgroClimateIndicator[] {
  return AGROCLIMATE_INDICATOR_SEED.map((def) => buildAgroClimateIndicator(def, now));
}
